### ISSUE TITLE
PHP warning from diff_node_view_alter() after installation

### ISSUE THREAD

**Issue by bradbulger** [backdrop-contrib/diff#8]
I've just enabled Diff and not done anything else. It looks like the default value for some config settings is NULL, when the code is expecting an array.

 On the home page node of my site, I'm seeing

Warning: in_array() expects parameter 2 to be array, null given in diff_node_view_alter() (line 314 of /path/to/backdrop/modules/contrib/diff/diff.module).

going to the Diff entities config tab, I get

Warning: Invalid argument supplied for foreach() in form_type_checkboxes_value() (line 2434 of /path/to/backdrop/core/includes/form.inc).

Saving the config pages, without making any changes, make the warnings there go away.

I enabled revisions on a content type but the home page warning is still there.

**Comment by Graham-72** [comment]
@bradbulger thanks for reporting this. I think this is now fixed by PR #9. Please kindly confirm and close this issue if OK.

**Comment by bradbulger** [comment]
I applied the patch and still had the issues. After uninstalling and reinstalling the module, I don't see any of the warnings or errors. I'd suggest adding an update function to fix existing settings. Is there a way I can submit a change to the PR?

**Comment by Graham-72** [comment]
A new release will have to include an update function to fix this and I suspect some other changes - work in progress.

**Comment by Graham-72** [comment]
@bradbulger Hopefully the new release (1.x-3.4.0) fixes this. I have included updates to carry forward any settings that were stored by the initial release 1.x-3.2.0 so hopefully a smooth update is possible.

**Comment by bradbulger** [comment]
I still see a couple of problems. No default is set for diff_show_diff_inline_node_bundles or diff_field_default_options. So the initial error reported here remains.

Also, in 3.2 it was possible to set values for the additional_options for node and user. The update_1001 hook clears them without saving any existing values. That's already out in the world, but it might be worth modifying it to save the existing config.

**Comment by klonos** [comment]
>Also, in 3.2 it was possible to set values for the additional_options for node and user. The update_1001 hook clears them without saving any existing values. That's already out in the world, but it might be worth modifying it to save the existing config.

https://backdropcms.org/project/usage/diff#project-usage-project-releases shows 34 sites already in 3.4.0 and only 4 sites in 3.2.0, but I agree that it's worth preventing the configuration loss for these 4 sites when they eventually upgrade.

I just reviewed and RTBC'ed https://github.com/backdrop-contrib/diff/pull/15

@Graham-72 are you around to review/merge this fix?

**Comment by quicksketch** [comment]
https://github.com/backdrop-contrib/diff/pull/15 has been merged and I'm not seeing any errors on PHP 8.3. I'll make a new release shortly.
